spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/keycloak/realms/test
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:8881/default_db
    username: root
    password: root
jwt:
  auth:
    converter:
      resource-id: first_client
      principal-attribute: preferred_username
logging:
  level:
    root: info
    org.springframework.security: DEBUG
corsAllowedOrigin: http://localhost:3000